Metrics/LineLength:
  Max: 100

Style/Documentation:
  Exclude:
    - "app/decorators/*.rb"
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"