version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432
    volumes:
      - .:/mini_blog
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    # entrypoint: /bin/bash
    # stdin_open: true
    # tty: true
